### ISSUE TITLE
Header row labels changed in 2019

### ISSUE THREAD

**Issue by wbw60** [nmfta-repo/pretty_1939#5]
Just a warning and FYI to those using later versions of the annex (2019_10 in my case), the labels changed (i.e. ACRONYM -> PG_ACRONYM, among others). So you will need to hack the scripts  for the later versions.

In addition, there is a new resolution with units of kW/s, I added a case to get_spn_resolution() to handle it (I copied the microsiemens/mm case logic).

And one last thing - I had to add this:
            if '=' not in line:
                continue
to the top of the for loop in get_enum_lines() to deal with the fact that one of the descriptions began with the number "13" but then used binary values for the enums, which led to the code thinking the values were not binary and trying to process '0000b' as an integer base 10. :-( 

It appears to have worked after these changes. 

Regards,
 Bill

**Comment by BenGardiner** [comment]
hi @wbw60 . can you share your changes to the `create_j1939db-json.py` please?

**Comment by wbw60** [comment]
Here's a diff (new version prefaced with "<")
+++++++++++++++++
`121,122d120
<         elif 'kw/s' in norm_contents:  # special handling for this new weirdness
<             return float(contents.split(' ')[0])
201,202d198
<             if '=' not in line:
<                 continue
295,297c287,289
<         acronym_col = header_row.index('PG_ACRONYM')
<         pgn_label_col = header_row.index('PG_LABEL')
<         pgn_data_length_col = header_row.index('PG_DATA_LENGTH')
---
>         acronym_col = header_row.index('ACRONYM')
>         pgn_label_col = header_row.index('PARAMETER_GROUP_LABEL')
>         pgn_data_length_col = header_row.index('PGN_DATA_LENGTH')
299,300c291,292
<         spn_position_in_pgn_col = header_row.index('SP_POSITION_IN_PG')
<         spn_name_col = header_row.index('SP_LABEL')
---
>         spn_position_in_pgn_col = header_row.index('SPN_POSITION_IN_PGN')
>         spn_name_col = header_row.index('SPN_NAME')
304c296
<         spn_length_col = header_row.index('SP_LENGTH')
---
>         spn_length_col = header_row.index('SPN_LENGTH')
307c299
<         spn_description_col = header_row.index('SP_DESCRIPTION')
---
>         spn_description_col = header_row.index('SPN_DESCRIPTION')`

+++++++++++++++++++++
Note that this is only guaranteed to work with the 2019_10 version. As SAE randomly changes the J1939 digital annex the code will have to be updated. :-( I guess that's their sales model. ``

**Comment by BenGardiner** [comment]
Thank you very much for the patch, @wbw60  this is now finally resolved in the main branch with the merge of #26
